### ISSUE TITLE
1.9 combat mode crash

### ISSUE THREAD

**Issue by desert-bard** [exult/exult#460] opened 2024-03-28 05:06 UTC
Hail and well met! 

Greetings all, first I'd like to say how much I enjoy Exult! It's a great enhancement to the games.

I've been using 1.8 for years to play BG and SI and it always worked fine. I then discovered there was an Ultima 6 remake available and wanted to try it out. It strongly suggests I use Exult 1.9 so I downloaded and installed the 3-19-24 snapshot. 

However now whenever I go into any game I get a crash to desktop whenever I go into combat mode and start fighting. If there's no enemies around I can go into combat mode and nothing happens but once a fight starts it will crash. 

I attached a DxDiag report and a BG save game where I'm about to fight some spiders if that helps. I had to change the extension on the save file to .txt to get it to attach. I have an ancient GeForce 210 graphics card, maybe it's too old? 

Could be a mod issue maybe. I have the BG key ring, Source Forge Isle and the U6 remake installed. I'll try removing some and see what happens.  

Thanks much and All Hail Lord British!  ( don't let Lady Yelinda hear you say that ).

[DxDiag.txt](https://github.com/exult/exult/files/14784086/DxDiag.txt)
[exult07bg.txt](https://github.com/exult/exult/files/14784096/exult07bg.txt)

**Comment by DominusExult** [comment] 2024-03-28 08:37
I cannot reproduce this on macOS and Wine. Can you attach stdout.txt and stderr.txt after it crashes? 
You can find these where the exult.cfg is saved to http://exult.info/faq.php#where_cfg

**Comment by i30817** [comment] 2024-03-28 16:30
This mod has a few additional problems in exult Linux (because of possible mismatching case in files replaced\shadowed by the mod), but in windows the only problem occurs if you're not using either a current (as in the master branch, not the last release) exult or a not last version of the mod.

Oh you also have to copy a cfg file to the parent directory, but if you made the mod work I'm assuming you did that.

**Comment by desert-bard** [comment] 2024-03-28 22:39
The mods seem to be working fine, here's a screenshot of SourceForge Island where I'm getting ready to blow up some powder kegs. 

![sourceforge_island](https://github.com/exult/exult/assets/165240720/46818f17-3577-4f37-bab9-808abad44d13)

If I detonate the kegs in 1.8 they explode, the gargoyle is killed and the game continues. In 1.9 the kegs will detonate, the explosion will start, and there are three frames of explosion animation and then the issue hits even though I'm not in combat mode and I take no damage from the explosion. From this I found I can also reproduce the issue by setting a powder keg next to an NPC and detonating it.   

On Serpent Isle if I stand in a fire field I will take damage hits, die, and get resurrected by the monks with no issue so it doesn't seem to be connected to taking damage... but then why did it happen when the gargoyle took damage from the explosion... would the gargoyle go into combat mode when the damage started and that somehow triggered it?

Thought it might be an audio issue from the combat sounds so I turned the sound off but no change. Tried some different video settings, no change. Tried removing the mods, no change. I'll see if I can find anything else.

**Comment by desert-bard** [comment] 2024-03-28 22:46
I think I might have something wrong and closed the thread by accident...

**Comment by DominusExult** [comment] 2024-03-28 22:57
I'm stumped. I just can't reproduce it, even though I tried with your simple way of exploding a keg next to an NPC

**Comment by wench** [comment] 2024-03-28 23:05
First thought Windows 7?
Tested that snapshot in Windows 11 and no problems with combat in SI.

**Comment by desert-bard** [comment] 2024-03-28 23:16
I'm thinking it's the game version, I'm using this one which I bought... oh my god, almost thirty years ago now, can you believe that... and most people today are probably using the GOG version which may be different. I think I'll get a GOG account and try their version, I'll let you know what happens. Hey come to think of it I have a Steam account too, I'll see if they have one.

Been great talking with you all, good to know there are still fans out there.  :)

Here's the version - remember when games came on CD? Much like album covers the artwork added to the lore.

![ultima-vii](https://github.com/exult/exult/assets/165240720/b529ac38-d9ac-4e78-aa8e-3af494eaf48c)

**Comment by desert-bard** [comment] 2024-03-28 23:21
Hmm, I have a Windows 11 computer at work... think I'll see if I can get the boss of the office for a couple hours tee hee...

**Comment by DominusExult** [comment] 2024-03-28 23:23
> First thought Windows 7? Tested that snapshot in Windows 11 and no problems with combat in SI.

I tried with virtual machines running Windows 32 and 64 bit and both work.

> I'm thinking it's the game version, I'm using this one which I bought...

This *should* be an ok version but testing another might be a good idea.

**Comment by desert-bard** [comment] 2024-03-29 00:43
Yeah it could be something to do with Windows 7, I checked the Event logs and when it happens I first get Event 1000, Application Error - 

Faulting application name: Exult.exe, version: 1.9.0.0, time stamp: 0x660373f3
Faulting module name: Exult.exe, version: 1.9.0.0, time stamp: 0x660373f3
Exception code: 0xc000001d
Fault offset: 0x00013dcb
Faulting process id: 0xd9c
Faulting application start time: 0x01da8169213fcbf0
Faulting application path: C:\Program Files (x86)\Exult\Exult.exe
Faulting module path: C:\Program Files (x86)\Exult\Exult.exe
Report Id: a32c4003-ed5c-11ee-8f77-a4badbe7f9e4


And after that I get Event 1005, Application Error -

Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Exult Ultima VII Engine because of this error.

I don't think I'm missing any files because 1.8 works fine.

**Comment by DominusExult** [comment] 2024-03-29 10:35
Can you make C:\Games\ultima\ULTIMA7 and C:\Games\ultima\Serpent available in a Zip along with your exult.cfg (http://exult.info/faq.php#where_cfg)? Dropbox or Google drive or or? You can send the link to forum@exult.info instead of making it public.
I'd really like to solve this :)

**Comment by wench** [comment] 2024-03-29 23:57
That event log entry strongly suggests this is not a problem with Exult but is due to Windows being unable to read part of Exult.exe and that caused the app crash.

Can you download the latest snapshot and install it to a new path. If it works, then I would suggest scanning your drive by running chkdsk c: /f /r as you might have a drive fault or corrupted filesystem

**Comment by Squig0473** [comment] 2024-09-20 16:25
I have this same crash with windows 7. go into combat and crash.  I have installed to various places. The crash on occurs if I use Snapshot v1.9.0.20240212 or newer builds. My Ultima IV is GOG's The Complete Ultima IV.

**Comment by wench** [comment] 2024-09-20 16:29
You should be using 1.10

**Comment by wench** [comment] 2024-09-21 02:34
Ok, I'm curious what cpu are you using? v1.9.0.20240212 introduced a compile flag change that upped the cpu requirements of the Windows build to x86-64-v2. This  change meant that Windows 64bit builds will no longer work on cpus older than First Gen Core i CPUs. If you are using Windows 7, I'm guessing you are using an older Core 2 CPU so this is likely the problem. Unless there is an objection I think this change should be reverted. @marzojr you made this change in b8b375d. Thoughts?

**Comment by Squig0473** [comment] 2024-09-21 04:34
Yes I am using a Core 2 Due 2.66GHz

**Comment by marzojr** [comment] 2024-09-21 08:50
> Unless there is an objection I think this should be changed. @marzojr you made this change in b8b375d. Thoughts? I think we should always target baseline x86-64 in 64 bit builds and 686 for 32 bit builds. There really is nothing in Exult that would really benefit from the capabilities of new x86-64 cpus. We originally made exult on 32 bit P6 class cpus. There is no need for such a recent cpu requirement.

There are actually a few minor things that benefit Exult: mostly, this would be better vector instructions being (potentially) used on scalers, and a `movbe` instructions being used on some input code instead of `mov` + `bswap`.

But for the most part this should be very minor, and I have no issues with reverting this flag.

Only now we have to ensure that our dependencies don't use any similar flags or we will see similar issues crop up anyway.

**Comment by DominusExult** [comment] 2024-09-21 09:40
The 1.10 release for Windows wasbuilt with „native“ as I didn’t set „SNAPSHOT=1“.
So if I understand that changeset correctly this shouldn’t be the culprit (unless it is introduced by a dependency).

@Squig0473 can you provide a savegame?

**Comment by wench** [comment] 2024-09-21 10:19
native means what you have in the system that compiled Exult. unless you compiled on a Core 2, gcc will be compiling to some newer march causing compatibility problems on Core 2 CPUs.

I'll change the makefile tomorrow. If anyone compiling from source wants to compile to a newer march they could set the makefile variable on the command line. I'm also planning on adding cupid code to version.cc so we can output the details of what exult is running on to stdout in case this sort of thing causes trouble in the future.

**Comment by DominusExult** [comment] 2024-09-21 10:23
ah, thanks for clarifying. I'm building in a VM so I have no clue what native actually was.

@Squig0473 a savegame would still be good but when the @wench changes things the following snasphot should be ready to test. I'll let you know when it lands.

**Comment by Squig0473** [comment] 2024-09-21 16:20
Okay Here are some save games

    On Saturday, September 21, 2024 at 05:23:38 AM CDT, Dominik Reichardt ***@***.***> wrote:  
 
 


ah, thanks for clarifying. I'm building in a VM so I have no clue what native actually was.

@Squig0473 a savegame would still be good but when the @wench changes things the following snasphot should be ready to test. I'll let you know when it lands.

**Comment by DominusExult** [comment] 2024-09-21 20:11
@Squig0473 these didn't come through. Mainly because Github doesn't accept the sav extension and perhaps because it was per email answer. Best zip them up and attach them to a reply. Sorry for the bother.

**Comment by Squig0473** [comment] 2024-09-21 20:28
[savegames.zip](https://github.com/user-attachments/files/17085656/savegames.zip)

Here are my save games. Must have been the email. i zipped them up the first time.

**Comment by DominusExult** [comment] 2024-09-21 20:43
thanks. I can't reproduce it, which really points at @wench's point. Just for completeness sake, can you also attach or copy/past your exult.cfg?

**Comment by Squig0473** [comment] 2024-09-21 21:21
[exult_config.zip](https://github.com/user-attachments/files/17085742/exult_onfig.zip)
Here is my config file

**Comment by DominusExult** [comment] 2024-09-21 21:37
Thank you. Alas no crash either for me :(

**Comment by wench** [comment] 2024-09-22 12:04
Pushed changes for this. Hopefully it fixes this

**Comment by wench** [comment] 2024-09-23 02:56
@Squig0473 please try the latest snapshot to see if it fixes your problem.

**Comment by wench** [comment] 2024-09-23 07:52
> Yeah it could be something to do with Windows 7, I checked the Event logs and when it happens I first get Event 1000, Application Error -
> 
> Faulting application name: Exult.exe, version: 1.9.0.0, time stamp: 0x660373f3 Faulting module name: Exult.exe, version: 1.9.0.0, time stamp: 0x660373f3 Exception code: 0xc000001d Fault offset: 0x00013dcb Faulting process id: 0xd9c Faulting application start time: 0x01da8169213fcbf0 Faulting application path: C:\Program Files (x86)\Exult\Exult.exe Faulting module path: C:\Program Files (x86)\Exult\Exult.exe Report Id: a32c4003-ed5c-11ee-8f77-a4badbe7f9e4
> 
> And after that I get Event 1005, Application Error -
> 
> Windows cannot access the file for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program Exult Ultima VII Engine because of this error.
> 
> I don't think I'm missing any files because 1.8 works fine.

Replying to this much earlier post the exception code listed here is Illegal  Instruction. I'm surprised I. didn't notice months ago

**Comment by Squig0473** [comment] 2024-09-23 18:59
Thank you it works now!!

**Comment by DominusExult** [comment] 2024-09-23 19:59
thank you for the swift testing!

seems we need a bugfix release of 1.10 soon.
Anyone care to merge recent commits back into the 1.10 branch? Beginning with 9b4fbdcf0. Though I guess there is no other way to do it than cherry picking from master.

**Comment by wench** [comment] 2024-09-23 23:54
Ok this is great news. Can finally close this as it seems like it Is fixed. Big thanks to @Squig0473  for spending the time to workout which snapshot broke things.

A Hot fix 1.10.1 update does seem essential right now.  for this and the mods installation fix

**Closed by wench** 2024-09-23 23:54 UTC

**Comment by wench** [comment] 2024-09-24 11:35
@DominusExult  I cherry picked my commits into the v1.10.x branch. I didn't do yours as they have conflicts and it seemed best if you dealt with those

**Comment by DominusExult** [comment] 2024-09-24 11:39
thanks, I will do those later today
