### ISSUE TITLE
SI: issues when restoring from savegame: missing state or UI frozen

### ISSUE THREAD

**Issue by psavola** [exult/exult#141] opened 2022-02-05 20:05 UTC
[saves.zip](https://github.com/exult/exult/files/8008836/saves.zip)
In my first playthrough (exult 1.7.0git Jan 24 2022) of Serpent Isle + Silver Seed, I noticed twice a problem after loading a game from savegame, as if some game state is lost or is not restored properly.

First issue, when reconstructing Boydon at Erstam. I had already inserted all the pieces and the phonix egg, except I had forgotten to insert the forearm. I had saved at this point. In the original game I inserted the missing forearm and Boyden was rebuilt. Now, restoring from save game and inserting the missing piece (on the right side in the room) there is no reaction, except the piece is accepted. I suppose that either the state of what items have already been successfully inserted has not been stored or the information is not properly restored?

Second issue just before the end. I had only inserted one of the serpent eyes on the pedastal before the statue and was struggling with getting the second one on there. In the main game I got struck by lightning and died off. After restoring, the UI appears to be stuck as if in the middle of a dialogue and I can't do anything with items, move, etc.

**Comment by DominusExult** [comment] 2022-02-06 14:04
I think part of the problem might be caused by the regressions I found the last two days #143 (thanks to your #142) and #140

**Comment by DominusExult** [comment] 2022-02-06 15:34
Could you give the newest git a try for a while? Marzo landed a fix right now that might fix parts of your problems.

**Comment by psavola** [comment] 2022-02-06 16:09
Both issues, at least when loading the game, still persist with the latest master snapshot. I don't know if the fix would have prevented these from happening in the first place.

**Comment by DominusExult** [comment] 2022-02-06 19:16
might be that these would not have happened, so if you are still playing it would be nice if you could keep an eye on it.

**Comment by psavola** [comment] 2022-02-13 16:31
Now playing with SIfixes and Feb 12 2022 code. In the savegame, insert a few pieces into the machine, quick save, load the quick save, insert the rest. Nothing happens. If you insert all at once, without reloading in between, it works fine. So at least the 'missing state' problem is there (no idea how the original behaves).
[exult05si.zip](https://github.com/exult/exult/files/8056064/exult05si.zip)

**Comment by DominusExult** [comment] 2022-02-13 19:34
I tested the original and it doesn't have that problem. We might have always had this problem :(

**Closed** 2023-03-26 17:03 UTC

**Comment by marzojr** [comment] 2023-03-26 17:08
The underlying bug causing Boydon's creation is fixed; i.e., the necessary state is saved now. The old save is still broken, though.
