### ISSUE TITLE
SI: Saving and loading resets puzzle in Temple of Order

### ISSUE THREAD

**Issue by Crowley9** [exult/exult#301] opened 2023-01-04 19:40 UTC
In the Temple of Order there is a puzzle where you are supposed to place a scroll about Ethicality, a serpent dagger and an abacus onto a pedestal to solve it and cause a door to open. I noticed that if you put some of the items there, then save and reload, the puzzle resets to where you need to begin with the scroll again. Even if after put all three there and open the door, saving and loading it still resets the pedestal! This is a nasty one as the items are consumed on the pedestal, so it could just leave the player completely stuck. I have attached a save that is right in front of the pedestal with the items present and ready to be placed there.

This is using Exult 1.9 snapshot 2022-12-25 with SI Fixes mod.

[OrderPuzzle.zip](https://github.com/exult/exult/files/10346968/OrderPuzzle.zip)

**Comment by DominusExult** [comment] 2023-01-06 21:25
It's a duplicate of #141 (as in saving and reloading breaks certain stuff)

**Closed by DominusExult** 2023-01-06 21:25 UTC

**Comment by DominusExult** [comment] 2024-04-09 20:05
This was fixed
