### ISSUE TITLE
Merge Audio into main release?

### ISSUE THREAD

**Issue by Dreded** [exult/exult#130] opened 2022-01-12 21:05 UTC
I understand 20 even 10years ago having the audio as a separate download made a ton of sense.. currently it takes me about 3 seconds to download it(if source forge wasn't slow Exult plus Audio is a sub 1 second download) so is there a reason its still a separate download?

I would argue nobody should be playing without it unless they have original hardware, so maybe make the audio one the default and offer a separate no audio option for these special cases(even they probably dont care about the extra 40mb)

Doing this would really streamline installation and make it so the default config could be what people want for an end result.

**Comment by DominusExult** [comment] 2022-01-12 21:26
I agree it doesn't make sense for releases, but for our "daily" snapshots it is a digital waste.
For example I'm keeping a collection of the macOS snapshots I did over the years (it makes regression testing a bit less painless to be able to pin a problem down, especially as most binaries from years ago still work but to use git bisect I could potentiall run into several compile issues that I would need to backport fixes for during each bisect step). I have 700 snapshots...

**Comment by Dreded** [comment] 2022-01-14 20:04
Not sure I understand, would simply have two copies of a release.. audio and no audio this doesn't take enough space up to matter, even on free services. Doesn't need to be created per person. Perhaps as a long term space saving measure have the older releases(older than 3 maybe) have only the without audio option(can still be a separate download)

I think as power users we significantly underestimate the average person ability to figure this all out, my nephew(31yrs old) saw me playing UltimaVII and as an RPG lover he said "hey that looks cool" so I told him where to go to install it an hour later he asked me if I could come help him as he had spent the last hour "trying to figure it out". That's a huge barrier to entry, someone who just wants to enjoy a piece of history shouldn't have to endure.

What Dominus is talking about im pretty sure is on his personal computer/personal server.

**Comment by DominusExult** [comment] 2022-01-14 20:11
Yes, on my personal computer/server but I'm doing the official snapshots in the case of macOS not the github actions (mostly because I need to sign the binaries with my developer key and I'm not saving that on github).

Did he read the FAQ and documentation? If yes, where did he stop understanding what to do? I'd love to make that more understandable.

**Comment by Dreded** [comment] 2022-01-14 20:23
Not sure, he managed to get exult pointed at the game files so that wasn't a barrier for him, but I think thats getting us off track as to my mind if someone has to RTFM to simply install the game in a way that is optimal then the User Experience is a failure.

**Comment by Dreded** [comment] 2022-01-14 20:29
A little more on track, could use an installer that will download the needed bits based on options selected inside the installer, for bandwidth concerned folks could just update the overall download size as things get checked off.

This would allow for optimal config files to be installed at the same time(user selects I have a 1080p LCD and poof options are setup for 1080p.

**Comment by DominusExult** [comment] 2022-01-15 00:23
Seems our installer (InnoSetup) has built in support to download files during installation since version 6.1 (released last year).

https://stackoverflow.com/q/6887428/850848#66100456

I'll toy a bit with this.

**Comment by DominusExult** [comment] 2022-01-17 20:18
with 75eb91cc I've added the option to download and install the audio files along with the mods (the mods require you to set the game paths in the installer).
Please wait for the next automated github snapshot release as the mods were not correctly zipped (fixed with 875cb567).

**Closed** 2022-01-18 17:49 UTC
