### ISSUE TITLE
Exult 1.9 Avatar shape doesn't exist (SI Fixes) and crashes when clicking Game Display

### ISSUE THREAD

**Issue by Skitz10** [exult/exult#325] opened 2023-03-17 23:40 UTC
Hi recently wanted to play Ultima Serpent Isle again!
running Exult 1.9
Serpent Isle fix mod Avatar shape doesn't exist just a floating spell book, New game btw
Also Exult crashes when clicking Game Display. No matter where I click it, Exult Setup. pressing esc in Black Gate or Serpent Isle and clicking Game Display. All 3 ways crash exult.

![Exult 1](https://user-images.githubusercontent.com/128194145/226070082-d798bb44-d5aa-4c67-9ea0-7aa27028cfcd.png)
![Exult 2](https://user-images.githubusercontent.com/128194145/226070107-8d895fbe-3002-4245-b224-4cf21480b56e.png)

**Comment by DominusExult** [comment] 2023-03-18 14:19
I cannot reproduce this with current snapshots of both Exult and the mods. I had messed up building of the snapshot of the last five days, but this is fixed now. So can you download the latest snapshots from https://github.com/exult/exult/releases?
Please make sure that you don't have a patch folder or other files in your mods folder.

If this persists, please delete/rename your exult.cfg and install Exult again (so it generates a new valid exult.cfg).

**Comment by Skitz10** [comment] 2023-03-18 17:02
pesky exult.cfg was the issue, Thank you very much!

**Comment by DominusExult** [comment] 2023-03-18 17:03
I'm glad it's working again!

**Closed by DominusExult** 2023-03-18 17:03 UTC
